// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqn39Bgh3J2yoFlvWy5zmHom-tZXUmV8Q',
    appId: '1:189103015572:web:bfb4edb94793dcc0679681',
    messagingSenderId: '189103015572',
    projectId: 'ica14-9144c',
    authDomain: 'ica14-9144c.firebaseapp.com',
    storageBucket: 'ica14-9144c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlsqz8IarFTWWwiKmjheyFEIoyh8Yr1g',
    appId: '1:189103015572:android:cba3447b27756612679681',
    messagingSenderId: '189103015572',
    projectId: 'ica14-9144c',
    storageBucket: 'ica14-9144c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_9XRYPn99H8qTOglYBcmOZkcHlaDbeY',
    appId: '1:189103015572:ios:2bb67dc3f6a50e33679681',
    messagingSenderId: '189103015572',
    projectId: 'ica14-9144c',
    storageBucket: 'ica14-9144c.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_9XRYPn99H8qTOglYBcmOZkcHlaDbeY',
    appId: '1:189103015572:ios:2bb67dc3f6a50e33679681',
    messagingSenderId: '189103015572',
    projectId: 'ica14-9144c',
    storageBucket: 'ica14-9144c.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqn39Bgh3J2yoFlvWy5zmHom-tZXUmV8Q',
    appId: '1:189103015572:web:8ad8a4e8a424de5e679681',
    messagingSenderId: '189103015572',
    projectId: 'ica14-9144c',
    authDomain: 'ica14-9144c.firebaseapp.com',
    storageBucket: 'ica14-9144c.firebasestorage.app',
  );
}
